1. Реализовано наследование шаблонов в проекте. Меню подключается как…
oshtyrov/geekshop-django pull request #2
Opened 2021-01-25 12:00 UTC by oshtyrov

1. Реализовано наследование шаблонов в проекте. Меню подключается как подшаблон.
2. Реализован механизмы работы со статическими файлами и url-адресами, которые прошли на уроке.
3. Проведена работа с шаблонными тегами и фильтрами (заглавные буквы, вывод текущей даты в шаблоне).
4. Организован вывод динамического контента на странице products.html.
5. Данные из json файла вытащил, но пока просто скопировал в views.py. Насколько понял, в дальнейшем, надо в отдельном файле выписать в ООП класс для продуктов, там распаковывать джейсон и потом этот файл подключать к views.py.

2021-01-25 15:20 UTC, Vokler requested changes

2021-01-25 15:20 UTC, Vokler commented on mainapp/views.py
> +            {'model': 'mainapp.product',
А откуда у вас модель появилась?) Мы еще не создавали какие-либо модели. Раз вы создали json файл с продуктами, лучше использовать его, нежели снова повторять тот же кусок кода тут.

2021-01-26 22:56 UTC, oshtyrov commented on mainapp/views.py
> +            {'model': 'mainapp.product',
Насчет модели - я просто распаковал джейсон фаил, не редактировал. Мне надо вносить правки, чтоб задание было зачтено?

2021-01-27 14:06 UTC, Vokler commented on mainapp/views.py
> +            {'model': 'mainapp.product',
Да, в этой же ветке

2021-01-28 10:14 UTC, oshtyrov commented on mainapp/views.py
> +            {'model': 'mainapp.product',
Не знаю, что делать. Я заменил словарь contens на
    with open("mainapp/fixtures/products.json") as read_f:
        data = json.load(read_f)[0]
        content = data
Если делаю принт data - выводит тот же словарь, но на странице продуктов теперь товары не отображается...

2021-01-28 10:21 UTC, oshtyrov commented on mainapp/views.py
> +            {'model': 'mainapp.product',
Не знаю что делать. Я заменил словарь content на 
    with open("mainapp/fixtures/products.json") as read_f:
        data = json.load(read_f)[0]
        content = data
Но теперь продукты на странице не отображаются. Выводу через принт словарь data - 
он идентичен изначальному словарю content...

2021-01-28 11:16 UTC, oshtyrov commented on mainapp/views.py
> +            {'model': 'mainapp.product',
Готово.

2021-01-28 11:19 UTC, merged