Lesson 4
oshtyrov/geekshop-django pull request #4
Opened 2021-02-03 16:42 UTC by oshtyrov

Добрый день! Пользователя создавал, логин, логаут работает. Спасибо за проверку.

2021-02-03 18:10 UTC, Vokler requested changes

2021-02-03 18:10 UTC, Vokler commented on authapp/urls.py
> +    path('/logout', logout, name='logout'),
А почему у вас слэш в начале? Он автоматически подставляется. А вот в конце обязательно должен быть.

2021-02-04 15:19 UTC, oshtyrov commented on authapp/urls.py
> +    path('/logout', logout, name='logout'),
Исправил.

2021-02-05 07:49 UTC, Vokler approved these changes

2021-02-05 07:49 UTC, merged